<a href="https://colab.research.google.com/github/malleeeek7-cpu/HomeWork2_python/blob/main/HomrWork2_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
from numpy import random

# Given Array
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("Given Array:")
print(arr)

print("\n1. Use indexing to print the element in the third row and first column")
print(arr[2, 0])

print("\n2. Use slicing to print the second column")
print(arr[:, 1])

print("\n3. Print the data type of the array elements")
print(arr.dtype)

print("\n4. Create a copy of the array, modify its first element, and check whether the original array is affected")
arr_copy = arr.copy()
arr_copy[0, 0] = 100
print("Copy:")
print(arr_copy)
print("Original:")
print(arr)

print("\n5. Create a view of the array, modify its first element, and check whether the original array is affected")
arr_view = arr.view()
arr_view[0, 0] = 200
print("View:")
print(arr_view)
print("Original:")
print(arr)

print("\n6. Print the shape of the array")
print(arr.shape)

print("\n7. Use a loop to print each element of the array")
for x in arr:
    for y in x:
        print(y)

print("\n8. Create a new array with the same shape and join it with the original array both vertically and horizontally")
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print("Vertical Join:")
print(np.vstack((arr, arr2)))
print("Horizontal Join:")
print(np.hstack((arr, arr2)))

print("\n9. Split the original array into three smaller arrays based on columns")
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

print("\n10. Search for the position of the value 60 in the array")
x = np.where(arr == 60)
print(x)

print("\n11. Sort each row of the array in ascending order")
print(np.sort(arr))

print("\n12. Use filtering to create a new array containing only elements greater than 50")
newarr2 = arr[arr > 50]
print(newarr2)

print("\n13. Generate a 2x3 array of random integers between 1 and 100")
print(random.randint(1, 100, size=(2, 3)))

print("\n14. Use a NumPy ufunc on the original array")
print(np.add(arr, 10))


Given Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

1. Use indexing to print the element in the third row and first column
70

2. Use slicing to print the second column
[20 50 80]

3. Print the data type of the array elements
int64

4. Create a copy of the array, modify its first element, and check whether the original array is affected
Copy:
[[100  20  30]
 [ 40  50  60]
 [ 70  80  90]]
Original:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

5. Create a view of the array, modify its first element, and check whether the original array is affected
View:
[[200  20  30]
 [ 40  50  60]
 [ 70  80  90]]
Original:
[[200  20  30]
 [ 40  50  60]
 [ 70  80  90]]

6. Print the shape of the array
(3, 3)

7. Use a loop to print each element of the array
200
20
30
40
50
60
70
80
90

8. Create a new array with the same shape and join it with the original array both vertically and horizontally
Vertical Join:
[[200  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [  1   2   3]
 [  4   5   6]
 [  7   8   9]]
Horizontal J